apiVersion: v1
kind: Pod
metadata:
  name: rdev
spec:
  serviceAccountName: private-user
  containers:
  - name: rdev
    image: private-docker-repo/rdev:0.1.0
    volumeMounts:
    - name: storage
      mountPath: /mnt
    - name: local-storage
      mountPath: /local-mnt
    command: ["sleep", "3600000"]
    resources:
      requests:
        memory: 5Gi
        cpu: 4
        ephemeral-storage: 10Gi
      limits:
        memory: 5Gi
        cpu: 4
        ephemeral-storage: 10Gi
    ports:
    - containerPort: 50051
  - name: kubectl-sidecar
    image: private-docker-repo/kubectl-sidecar:0.1.0
    ports:
    - containerPort: 8001
  volumes:
  - name: local-storage
    emptyDir: {}
  - name: storage
    persistentVolumeClaim:
      claimName: executables 

